import { containerTokens } from "@/configuration/bootstrap/container";
import type { OrganizationsController } from "@/features/organizations/organizations.controller";
import type { RouteModule } from "@/configuration/bootstrap/routes/types";

export const organizationsRouteModule: RouteModule = {
  id: "organizations",
  register(app, { resolveHandler }) {
    app.get(
      "/organizations",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "list",
      ),
    );
    app.post(
      "/organizations",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "create",
      ),
    );
    app.get(
      "/organizations/me",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "listMine",
      ),
    );
    app.post(
      "/organizations/me/active",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "setActive",
      ),
    );
    app.get(
      "/organizations/invitations/:token",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "previewInvitation",
      ),
    );
    app.post(
      "/organizations/invitations/:token/accept",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "acceptInvitation",
      ),
    );
    app.get(
      "/organizations/:id/workspace",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "getWorkspaceById",
      ),
    );
    app.get(
      "/organizations/:id",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "getById",
      ),
    );
    app.get(
      "/organizations/:id/audit",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "listAudit",
      ),
    );
    app.post(
      "/organizations/:id/audit/:auditId/restore",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "restoreAuditEntry",
      ),
    );
    app.get(
      "/organizations/:id/announcements",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "listAnnouncements",
      ),
    );
    app.post(
      "/organizations/:id/announcements",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "createAnnouncement",
      ),
    );
    app.patch(
      "/organizations/:id/announcements/:announcementId",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "updateAnnouncement",
      ),
    );
    app.delete(
      "/organizations/:id/announcements/:announcementId",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "deleteAnnouncement",
      ),
    );
    // Public, unauthenticated global blog feed/search across all organizations
    // (Elasticsearch-backed, published posts only).
    app.get(
      "/blog",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "searchPublicBlogFeed",
      ),
    );
    // Public, unauthenticated per-organization blog reads (published posts only).
    app.get(
      "/organizations/:id/blog",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "listPublicBlogPosts",
      ),
    );
    app.get(
      "/organizations/:id/blog/:slug",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "getPublicBlogPost",
      ),
    );
    // Authenticated, manager-gated blog management.
    app.get(
      "/organizations/:id/blog-posts",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "listBlogPosts",
      ),
    );
    app.post(
      "/organizations/:id/blog-posts",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "createBlogPost",
      ),
    );
    app.patch(
      "/organizations/:id/blog-posts/:blogPostId",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "updateBlogPost",
      ),
    );
    app.delete(
      "/organizations/:id/blog-posts/:blogPostId",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "deleteBlogPost",
      ),
    );
    // Public, unauthenticated review reads.
    app.get(
      "/organizations/:id/reviews",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "listReviews",
      ),
    );
    // Authenticated reviewer submission (renters with a completed rental).
    app.get(
      "/organizations/:id/reviews/me",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "getOwnReview",
      ),
    );
    app.post(
      "/organizations/:id/reviews",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "createReview",
      ),
    );
    app.put(
      "/organizations/:id/reviews/me",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "updateOwnReview",
      ),
    );
    app.delete(
      "/organizations/:id/reviews/me",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "deleteOwnReview",
      ),
    );
    // Manager-gated review moderation.
    app.put(
      "/organizations/:id/reviews/:reviewId/reply",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "replyToReview",
      ),
    );
    app.delete(
      "/organizations/:id/reviews/:reviewId/reply",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "removeReviewReply",
      ),
    );
    app.delete(
      "/organizations/:id/reviews/:reviewId",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "deleteReview",
      ),
    );
    app.patch(
      "/organizations/:id",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "update",
      ),
    );
    app.post(
      "/organizations/:id/invitations",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "createInvitation",
      ),
    );
    app.delete(
      "/organizations/:id/invitations/:inviteId",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "revokeInvitation",
      ),
    );
    app.patch(
      "/organizations/:id/members/:memberId",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "updateMemberRole",
      ),
    );
    app.delete(
      "/organizations/:id/members/:memberId",
      resolveHandler<OrganizationsController>(
        containerTokens.organizationsController,
        "removeMember",
      ),
    );
  },
};
