import BadRequestError from "@/errors/http/bad-request.error";
import ResourceNotFoundError from "@/errors/http/resource-not-found.error";
import UsernameChangeCooldownError from "@/errors/http/username-change-cooldown.error";
import type { IdentityBloomService } from "@/features/auth/identity-bloom/identity-bloom.service";
import type { UsernameService } from "@/features/auth/username/username.service";
import type { MediaService } from "@/features/media/media.service";
import type {
  ListProfilesInput,
  ListProfilesResult,
  ProfileRecord,
  UpdateProfileInput,
  UpdateProfileRecordInput,
} from "@/features/profile/profile.model";
import type { ProfileRepository } from "@/features/profile/profile.repository";
import {
  isSameUsername,
  resolveUsernameChangeEligibility,
  USERNAME_CHANGE_COOLDOWN_DAYS,
} from "@/features/profile/username-change-policy";
import type { Uuid } from "@/configuration/validation/uuid";

export class ProfileService {
  constructor(
    private readonly profileRepository: ProfileRepository,
    private readonly mediaService: MediaService,
    private readonly usernameService: UsernameService,
    private readonly usernameBloomService: IdentityBloomService,
  ) {}

  async list(input: ListProfilesInput): Promise<ListProfilesResult> {
    return this.profileRepository.findPublicProfiles({
      page: input.page,
      pageSize: input.pageSize,
      query: input.query?.trim() || undefined,
    });
  }

  async getByUserId(userId: Uuid): Promise<ProfileRecord> {
    const profile = await this.profileRepository.findByUserId(userId);

    if (!profile) {
      throw new ResourceNotFoundError("Profile could not be found.");
    }

    return profile;
  }

  async update(requested: UpdateProfileInput): Promise<ProfileRecord> {
    this.assertPostingCounts(requested);
    this.assertAvatarFields(requested);

    const existingProfile = await this.profileRepository.findByUserId(
      requested.userId,
    );

    if (!existingProfile) {
      throw new ResourceNotFoundError("Profile could not be found.");
    }

    this.assertAvatarIsStored(requested, existingProfile);
    const input = await this.resolveAvatarMedia(requested);

    const username = input.username.trim().toLowerCase();
    // `username` is required on every profile PUT, so a phone or avatar save
    // resends the current value. Only a genuine change may spend the cooldown.
    const isRename = !isSameUsername(username, existingProfile.username);

    const updated = await this.profileRepository.update({
      ...input,
      username,
      ...(isRename
        ? await this.resolveUsernameChange(existingProfile, username)
        : {}),
      // An omitted field (`undefined`) means "not part of this update" and must
      // leave the stored value alone. Only an explicit `null` or a blank string
      // clears it. Collapsing the two used to make the account page's "Save
      // profile" — which sends neither — wipe the saved phone number and avatar.
      ...(input.phoneNumber !== undefined
        ? { phoneNumber: input.phoneNumber?.trim() || null }
        : {}),
      ...(input.avatarUrl !== undefined
        ? { avatarUrl: input.avatarUrl?.trim() || null }
        : {}),
      ...(input.avatarBlobName !== undefined
        ? { avatarBlobName: input.avatarBlobName?.trim() || null }
        : {}),
    });

    if (!updated) {
      // The guarded write matched no row: a concurrent rename won the race and
      // stamped the clock between our read and our write.
      throw await this.buildLostRaceError(input.userId);
    }

    if (isRename) {
      // Only the new name is recorded. The old one stays in the filter because
      // a bloom filter cannot forget, which costs one wasted query for whoever
      // tries to claim it until the next rebuild drops it.
      await this.usernameBloomService.add(username);
    }

    return updated;
  }

  /**
   * Builds the cooldown error for a rename that lost a concurrent race, using
   * the row as it stands now so the reported `availableAt` reflects the rename
   * that actually landed.
   */
  private async buildLostRaceError(userId: Uuid): Promise<Error> {
    const current = await this.profileRepository.findByUserId(userId);

    if (!current) {
      return new ResourceNotFoundError("Profile could not be found.");
    }

    const eligibility = resolveUsernameChangeEligibility({
      usernameChangedAt: current.usernameChangedAt
        ? new Date(current.usernameChangedAt)
        : null,
      usernameAutoGenerated: current.usernameAutoGenerated,
    });

    return new UsernameChangeCooldownError(undefined, {
      availableAt: eligibility.availableAt?.toISOString(),
      retryAfterSeconds: eligibility.retryAfterSeconds,
      cooldownDays: USERNAME_CHANGE_COOLDOWN_DAYS,
    });
  }

  /**
   * Validates a rename and returns the cooldown bookkeeping to persist with it.
   *
   * Replacing an OAuth-generated username is a *claim* rather than a *change*:
   * the person never chose the original, so it clears the flag without starting
   * the clock.
   */
  private async resolveUsernameChange(
    existingProfile: ProfileRecord,
    username: string,
  ): Promise<
    Pick<
      UpdateProfileRecordInput,
      "usernameChangedAt" | "usernameAutoGenerated" | "usernameChangeGuardAt"
    >
  > {
    const eligibility = resolveUsernameChangeEligibility({
      usernameChangedAt: existingProfile.usernameChangedAt
        ? new Date(existingProfile.usernameChangedAt)
        : null,
      usernameAutoGenerated: existingProfile.usernameAutoGenerated,
    });

    if (!eligibility.canChange) {
      throw new UsernameChangeCooldownError(undefined, {
        availableAt: eligibility.availableAt?.toISOString(),
        retryAfterSeconds: eligibility.retryAfterSeconds,
        cooldownDays: USERNAME_CHANGE_COOLDOWN_DAYS,
      });
    }

    await this.usernameService.assertUsernameIsAvailable(
      username,
      existingProfile.userId,
    );

    // The check above is only advisory — it gives a precise error message from a
    // read. `usernameChangeGuardAt` is what actually enforces the rule, by
    // re-testing eligibility inside the write.
    const now = new Date();

    if (existingProfile.usernameAutoGenerated) {
      return { usernameAutoGenerated: false, usernameChangeGuardAt: now };
    }

    return { usernameChangedAt: now, usernameChangeGuardAt: now };
  }

  private assertPostingCounts(input: UpdateProfileInput): void {
    if (
      input.rentPostingsCount !== undefined &&
      input.availableRentPostingsCount !== undefined &&
      input.availableRentPostingsCount > input.rentPostingsCount
    ) {
      throw new BadRequestError(
        "Available rent postings count cannot exceed total rent postings count.",
      );
    }
  }

  private assertAvatarFields(input: UpdateProfileInput): void {
    if (input.avatarMediaId && (input.avatarUrl || input.avatarBlobName)) {
      throw new BadRequestError(
        "Send either avatarMediaId or avatarUrl and avatarBlobName, not both.",
      );
    }

    const hasAvatarUrl = input.avatarUrl !== undefined;
    const hasAvatarBlobName = input.avatarBlobName !== undefined;

    if (hasAvatarUrl !== hasAvatarBlobName) {
      throw new BadRequestError(
        "Avatar URL and avatar blob name must be provided together when updating the avatar.",
      );
    }

    if (!hasAvatarUrl && !hasAvatarBlobName) {
      return;
    }

    if (!input.avatarUrl && !input.avatarBlobName) {
      return;
    }

    if (!input.avatarUrl || !input.avatarBlobName) {
      throw new BadRequestError(
        "Avatar URL and avatar blob name must both be set or both be null.",
      );
    }

    if (!this.mediaService.isConfigured()) {
      throw new BadRequestError(
        "Avatar images require Azure Blob Storage to be configured on the backend.",
      );
    }

    if (
      !this.mediaService.isManagedUrl(input.avatarUrl, input.avatarBlobName)
    ) {
      throw new BadRequestError(
        "Avatar URL must match the Azure Blob Storage location for the provided blob name.",
      );
    }
  }

  // A new avatar arrives as a media id and resolves to its processed image.
  private async resolveAvatarMedia(
    input: UpdateProfileInput,
  ): Promise<UpdateProfileInput> {
    const { avatarMediaId, ...rest } = input;

    if (!avatarMediaId) {
      return rest;
    }

    const image = await this.mediaService.resolveAttachableImage(
      input.userId,
      avatarMediaId,
    );

    return {
      ...rest,
      avatarUrl: image.blobUrl,
      avatarBlobName: image.blobName,
    };
  }

  // Re-sending the stored avatar is always allowed, which is what every profile
  // save that leaves the avatar alone does. A new avatar only arrives as
  // avatarMediaId.
  private assertAvatarIsStored(
    input: UpdateProfileInput,
    existingProfile: ProfileRecord,
  ): void {
    const avatarBlobName = input.avatarBlobName?.trim();

    if (!avatarBlobName || avatarBlobName === existingProfile.avatarBlobName) {
      return;
    }

    throw new BadRequestError(
      "A new avatar must be uploaded and sent as avatarMediaId.",
    );
  }
}
