import { Prisma } from "@/generated/prisma/client";
import { BaseRepository } from "@/features/base/base.repository";
import ConflictError from "@/errors/http/conflict.error";
import type {
  ListProfilesInput,
  ListProfilesResult,
  ProfileRecord,
  PublicProfileRecord,
  UpdateProfileRecordInput,
} from "@/features/profile/profile.model";
import {
  resolveUsernameChangeEligibility,
  USERNAME_CHANGE_COOLDOWN_MS,
} from "@/features/profile/username-change-policy";

type ProfilePersistence = {
  id: string;
  userId: string;
  username: string;
  usernameChangedAt?: Date | null;
  usernameAutoGenerated?: boolean;
  phoneNumber: string | null;
  avatarUrl: string | null;
  avatarBlobName: string | null;
  isPrivate: boolean;
  recommendationPersonalizationEnabled?: boolean;
  trustworthinessScore: number;
  rentPostingsCount: number;
  availableRentPostingsCount: number;
  createdAt: Date;
  updatedAt: Date;
  user: {
    email: string;
    firstName: string | null;
    lastName: string | null;
  };
};

export class ProfileRepository extends BaseRepository {
  async findPublicProfiles(
    input: ListProfilesInput,
  ): Promise<ListProfilesResult> {
    const where: Prisma.ProfileWhereInput = {
      isPrivate: false,
      ...(input.query
        ? {
            OR: [
              {
                username: {
                  contains: input.query,
                },
              },
              {
                phoneNumber: {
                  contains: input.query,
                },
              },
              {
                user: {
                  is: {
                    email: {
                      contains: input.query,
                    },
                  },
                },
              },
              {
                user: {
                  is: {
                    firstName: {
                      contains: input.query,
                    },
                  },
                },
              },
              {
                user: {
                  is: {
                    lastName: {
                      contains: input.query,
                    },
                  },
                },
              },
            ],
          }
        : {}),
    };
    const skip = (input.page - 1) * input.pageSize;

    const [profiles, total] = await Promise.all([
      this.executeAsync(() =>
        this.prisma.profile.findMany({
          where,
          skip,
          take: input.pageSize,
          orderBy: [
            {
              trustworthinessScore: "desc",
            },
            {
              username: "asc",
            },
          ],
          include: {
            user: {
              select: {
                email: true,
                firstName: true,
                lastName: true,
              },
            },
          },
        }),
      ),
      this.executeAsync(() => this.prisma.profile.count({ where })),
    ]);

    const totalPages = Math.max(1, Math.ceil(total / input.pageSize));

    return {
      profiles: profiles.map((profile) => this.mapPublicProfile(profile)),
      pagination: {
        page: input.page,
        pageSize: input.pageSize,
        total,
        totalPages,
        hasNextPage: input.page < totalPages,
        hasPreviousPage: input.page > 1,
      },
      ...(input.query ? { query: input.query } : {}),
    };
  }

  async findByUserId(userId: string): Promise<ProfileRecord | null> {
    const profile = await this.executeAsync(() =>
      this.prisma.profile.findUnique({
        where: {
          userId,
        },
        include: {
          user: {
            select: {
              email: true,
              firstName: true,
              lastName: true,
            },
          },
        },
      }),
    );

    if (!profile) {
      return null;
    }

    return this.mapProfile(profile);
  }

  async findRecommendationPersonalizationEnabledByUserId(
    userId: string,
  ): Promise<boolean | null> {
    const prismaProfile = this.prisma.profile as unknown as {
      findUnique: (args: unknown) => Promise<{
        recommendationPersonalizationEnabled?: boolean;
      } | null>;
    };
    const profile = await this.executeAsync(() =>
      prismaProfile.findUnique({
        where: {
          userId,
        },
        select: {
          recommendationPersonalizationEnabled: true,
        },
      }),
    );

    return profile?.recommendationPersonalizationEnabled ?? true;
  }

  /**
   * Returns `null` only when a guarded rename lost a concurrent race — the row
   * no longer satisfied the cooldown condition by the time the write ran.
   */
  async update(input: UpdateProfileRecordInput): Promise<ProfileRecord | null> {
    try {
      const data = this.buildUpdateData(input);

      if (input.usernameChangeGuardAt) {
        return await this.updateEligibleForRename(input, data);
      }

      const prismaProfile = this.prisma.profile as unknown as {
        update: (args: unknown) => Promise<ProfilePersistence>;
      };
      const profile = await this.executeAsync(() =>
        prismaProfile.update({
          where: {
            userId: input.userId,
          },
          data,
          include: {
            user: {
              select: {
                email: true,
                firstName: true,
                lastName: true,
              },
            },
          },
        }),
      );

      return this.mapProfile(profile);
    } catch (error) {
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === "P2002"
      ) {
        throw new ConflictError("That username is already taken.");
      }

      throw error;
    }
  }

  private buildUpdateData(
    input: UpdateProfileRecordInput,
  ): Record<string, unknown> {
    return {
      username: input.username,
      // Only present when the service determined this is a real rename;
      // an ordinary profile save must not touch the cooldown columns.
      ...(input.usernameChangedAt !== undefined
        ? { usernameChangedAt: input.usernameChangedAt }
        : {}),
      ...(input.usernameAutoGenerated !== undefined
        ? { usernameAutoGenerated: input.usernameAutoGenerated }
        : {}),
      ...(input.phoneNumber !== undefined
        ? { phoneNumber: input.phoneNumber }
        : {}),
      ...(input.isPrivate !== undefined ? { isPrivate: input.isPrivate } : {}),
      ...(input.recommendationPersonalizationEnabled !== undefined
        ? {
            recommendationPersonalizationEnabled:
              input.recommendationPersonalizationEnabled,
          }
        : {}),
      ...(input.avatarUrl !== undefined ? { avatarUrl: input.avatarUrl } : {}),
      ...(input.avatarBlobName !== undefined
        ? { avatarBlobName: input.avatarBlobName }
        : {}),
      ...(input.trustworthinessScore !== undefined
        ? { trustworthinessScore: input.trustworthinessScore }
        : {}),
      ...(input.rentPostingsCount !== undefined
        ? { rentPostingsCount: input.rentPostingsCount }
        : {}),
      ...(input.availableRentPostingsCount !== undefined
        ? { availableRentPostingsCount: input.availableRentPostingsCount }
        : {}),
    };
  }

  /**
   * Applies a rename only while the row still satisfies the cooldown rule.
   *
   * The eligibility test lives in the `WHERE` clause so the database evaluates
   * it and writes in one statement. Two concurrent renames therefore serialize:
   * the winner stamps `usernameChangedAt`, and the loser's `WHERE` no longer
   * matches, so it updates nothing and gets `null` back.
   */
  private async updateEligibleForRename(
    input: UpdateProfileRecordInput,
    data: Record<string, unknown>,
  ): Promise<ProfileRecord | null> {
    const guardAt = input.usernameChangeGuardAt as Date;
    const cooldownCutoff = new Date(
      guardAt.getTime() - USERNAME_CHANGE_COOLDOWN_MS,
    );
    const prismaProfile = this.prisma.profile as unknown as {
      updateMany: (args: unknown) => Promise<{ count: number }>;
    };

    const result = await this.executeAsync(() =>
      prismaProfile.updateMany({
        where: {
          userId: input.userId,
          OR: [
            { usernameAutoGenerated: true },
            { usernameChangedAt: null },
            { usernameChangedAt: { lte: cooldownCutoff } },
          ],
        },
        data,
      }),
    );

    if (result.count === 0) {
      return null;
    }

    // Safe to read separately: the guard has already been decided, and it now
    // blocks any further rename, so nothing can move underneath this read.
    return this.findByUserId(input.userId);
  }

  private mapProfile(profile: ProfilePersistence): ProfileRecord {
    const eligibility = resolveUsernameChangeEligibility({
      usernameChangedAt: profile.usernameChangedAt ?? null,
      usernameAutoGenerated: profile.usernameAutoGenerated ?? false,
    });

    return {
      id: profile.id,
      userId: profile.userId,
      email: profile.user.email,
      firstName: profile.user.firstName ?? undefined,
      lastName: profile.user.lastName ?? undefined,
      username: profile.username,
      usernameChangedAt: profile.usernameChangedAt?.toISOString(),
      usernameAutoGenerated: profile.usernameAutoGenerated ?? false,
      canChangeUsername: eligibility.canChange,
      usernameChangeAvailableAt:
        eligibility.availableAt?.toISOString() ?? undefined,
      phoneNumber: profile.phoneNumber ?? undefined,
      avatarUrl: profile.avatarUrl ?? undefined,
      avatarBlobName: profile.avatarBlobName ?? undefined,
      isPrivate: profile.isPrivate,
      recommendationPersonalizationEnabled:
        profile.recommendationPersonalizationEnabled ?? true,
      trustworthinessScore: profile.trustworthinessScore,
      rentPostingsCount: profile.rentPostingsCount,
      availableRentPostingsCount: profile.availableRentPostingsCount,
      createdAt: profile.createdAt.toISOString(),
      updatedAt: profile.updatedAt.toISOString(),
    };
  }

  private mapPublicProfile(profile: ProfilePersistence): PublicProfileRecord {
    return {
      id: profile.id,
      userId: profile.userId,
      email: profile.user.email,
      firstName: profile.user.firstName ?? undefined,
      lastName: profile.user.lastName ?? undefined,
      username: profile.username,
      phoneNumber: profile.phoneNumber ?? undefined,
      avatarUrl: profile.avatarUrl ?? undefined,
      trustworthinessScore: profile.trustworthinessScore,
      rentPostingsCount: profile.rentPostingsCount,
      availableRentPostingsCount: profile.availableRentPostingsCount,
      createdAt: profile.createdAt.toISOString(),
      updatedAt: profile.updatedAt.toISOString(),
    };
  }
}
