import BadRequestError from "@/errors/http/bad-request.error";
import ConflictError from "@/errors/http/conflict.error";
import ResourceNotFoundError from "@/errors/http/resource-not-found.error";
import UsernameChangeCooldownError from "@/errors/http/username-change-cooldown.error";
import { getPendingSignupUsernameKey } from "@/features/auth/pending-signup-username";
import type { BlobService } from "@/features/blob/blob.service";
import type { CacheService } from "@/features/cache/cache.service";
import type {
  ListProfilesInput,
  ListProfilesResult,
  ProfileRecord,
  UpdateProfileInput,
  UpdateProfileRecordInput,
} from "@/features/profile/profile.model";
import type { ProfileRepository } from "@/features/profile/profile.repository";
import {
  isSameUsername,
  resolveUsernameChangeEligibility,
  USERNAME_CHANGE_COOLDOWN_DAYS,
} from "@/features/profile/username-change-policy";

export class ProfileService {
  constructor(
    private readonly profileRepository: ProfileRepository,
    private readonly blobService: BlobService,
    private readonly cacheService: CacheService,
  ) {}

  async list(input: ListProfilesInput): Promise<ListProfilesResult> {
    return this.profileRepository.findPublicProfiles({
      page: input.page,
      pageSize: input.pageSize,
      query: input.query?.trim() || undefined,
    });
  }

  async getByUserId(userId: string): Promise<ProfileRecord> {
    const profile = await this.profileRepository.findByUserId(userId);

    if (!profile) {
      throw new ResourceNotFoundError("Profile could not be found.");
    }

    return profile;
  }

  async update(input: UpdateProfileInput): Promise<ProfileRecord> {
    this.assertPostingCounts(input);
    this.assertAvatarFields(input);

    const existingProfile = await this.profileRepository.findByUserId(
      input.userId,
    );

    if (!existingProfile) {
      throw new ResourceNotFoundError("Profile could not be found.");
    }

    const username = input.username.trim().toLowerCase();
    // `username` is required on every profile PUT, so a phone or avatar save
    // resends the current value. Only a genuine change may spend the cooldown.
    const isRename = !isSameUsername(username, existingProfile.username);

    const updated = await this.profileRepository.update({
      ...input,
      username,
      ...(isRename
        ? await this.resolveUsernameChange(existingProfile, username)
        : {}),
      phoneNumber: input.phoneNumber?.trim() || null,
      avatarUrl: input.avatarUrl?.trim() || null,
      avatarBlobName: input.avatarBlobName?.trim() || null,
    });

    if (!updated) {
      // The guarded write matched no row: a concurrent rename won the race and
      // stamped the clock between our read and our write.
      throw await this.buildLostRaceError(input.userId);
    }

    return updated;
  }

  /**
   * Builds the cooldown error for a rename that lost a concurrent race, using
   * the row as it stands now so the reported `availableAt` reflects the rename
   * that actually landed.
   */
  private async buildLostRaceError(userId: string): Promise<Error> {
    const current = await this.profileRepository.findByUserId(userId);

    if (!current) {
      return new ResourceNotFoundError("Profile could not be found.");
    }

    const eligibility = resolveUsernameChangeEligibility({
      usernameChangedAt: current.usernameChangedAt
        ? new Date(current.usernameChangedAt)
        : null,
      usernameAutoGenerated: current.usernameAutoGenerated,
    });

    return new UsernameChangeCooldownError(undefined, {
      availableAt: eligibility.availableAt?.toISOString(),
      retryAfterSeconds: eligibility.retryAfterSeconds,
      cooldownDays: USERNAME_CHANGE_COOLDOWN_DAYS,
    });
  }

  /**
   * Validates a rename and returns the cooldown bookkeeping to persist with it.
   *
   * Replacing an OAuth-generated username is a *claim* rather than a *change*:
   * the person never chose the original, so it clears the flag without starting
   * the clock.
   */
  private async resolveUsernameChange(
    existingProfile: ProfileRecord,
    username: string,
  ): Promise<
    Pick<
      UpdateProfileRecordInput,
      "usernameChangedAt" | "usernameAutoGenerated" | "usernameChangeGuardAt"
    >
  > {
    const eligibility = resolveUsernameChangeEligibility({
      usernameChangedAt: existingProfile.usernameChangedAt
        ? new Date(existingProfile.usernameChangedAt)
        : null,
      usernameAutoGenerated: existingProfile.usernameAutoGenerated,
    });

    if (!eligibility.canChange) {
      throw new UsernameChangeCooldownError(undefined, {
        availableAt: eligibility.availableAt?.toISOString(),
        retryAfterSeconds: eligibility.retryAfterSeconds,
        cooldownDays: USERNAME_CHANGE_COOLDOWN_DAYS,
      });
    }

    await this.assertUsernameNotReservedByPendingSignup(username);

    // The check above is only advisory — it gives a precise error message from a
    // read. `usernameChangeGuardAt` is what actually enforces the rule, by
    // re-testing eligibility inside the write.
    const now = new Date();

    if (existingProfile.usernameAutoGenerated) {
      return { usernameAutoGenerated: false, usernameChangeGuardAt: now };
    }

    return { usernameChangedAt: now, usernameChangeGuardAt: now };
  }

  /**
   * Signup soft-reserves a username in the cache until its verification OTP
   * expires. Honouring it here keeps the rename path agreeing with both signup
   * and the availability endpoint, which would otherwise report a reserved name
   * as free.
   */
  private async assertUsernameNotReservedByPendingSignup(
    username: string,
  ): Promise<void> {
    const pendingSignupEmail = await this.cacheService.getJson<string>(
      getPendingSignupUsernameKey(username),
    );

    if (pendingSignupEmail) {
      throw new ConflictError("That username is already taken.", {
        field: "username",
      });
    }
  }

  private assertPostingCounts(input: UpdateProfileInput): void {
    if (
      input.rentPostingsCount !== undefined &&
      input.availableRentPostingsCount !== undefined &&
      input.availableRentPostingsCount > input.rentPostingsCount
    ) {
      throw new BadRequestError(
        "Available rent postings count cannot exceed total rent postings count.",
      );
    }
  }

  private assertAvatarFields(input: UpdateProfileInput): void {
    const hasAvatarUrl = input.avatarUrl !== undefined;
    const hasAvatarBlobName = input.avatarBlobName !== undefined;

    if (hasAvatarUrl !== hasAvatarBlobName) {
      throw new BadRequestError(
        "Avatar URL and avatar blob name must be provided together when updating the avatar.",
      );
    }

    if (!hasAvatarUrl && !hasAvatarBlobName) {
      return;
    }

    if (!input.avatarUrl && !input.avatarBlobName) {
      return;
    }

    if (!input.avatarUrl || !input.avatarBlobName) {
      throw new BadRequestError(
        "Avatar URL and avatar blob name must both be set or both be null.",
      );
    }

    if (!this.blobService.isConfigured()) {
      throw new BadRequestError(
        "Avatar images require Azure Blob Storage to be configured on the backend.",
      );
    }

    if (
      !this.blobService.isManagedBlobUrl(input.avatarUrl, input.avatarBlobName)
    ) {
      throw new BadRequestError(
        "Avatar URL must match the Azure Blob Storage location for the provided blob name.",
      );
    }
  }
}
