/**
 * Username rename cooldown.
 *
 * Usernames are public identity and double as the sign-in / account-recovery
 * handle, so a rename is rate limited to once per {@link USERNAME_CHANGE_COOLDOWN_DAYS}
 * days. This module is pure so the service, the tests and the seeds can all
 * agree on the rule without reaching for a clock or a database.
 */

export const USERNAME_CHANGE_COOLDOWN_DAYS = 30;

export const USERNAME_CHANGE_COOLDOWN_MS =
  USERNAME_CHANGE_COOLDOWN_DAYS * 24 * 60 * 60 * 1000;

export interface UsernameChangeEligibilityInput {
  /** When the cooldown clock last started. `null` means no cooldown is in effect. */
  usernameChangedAt: Date | null;
  /** True while the profile still carries the username generated for it at OAuth signup. */
  usernameAutoGenerated: boolean;
  now?: Date;
}

export interface UsernameChangeEligibility {
  canChange: boolean;
  /** When the next rename becomes possible, or `null` if it already is. */
  availableAt: Date | null;
  /** Seconds until `availableAt`, or 0 if the rename is possible now. */
  retryAfterSeconds: number;
}

const ELIGIBLE: UsernameChangeEligibility = {
  canChange: true,
  availableAt: null,
  retryAfterSeconds: 0,
};

export function resolveUsernameChangeEligibility(
  input: UsernameChangeEligibilityInput,
): UsernameChangeEligibility {
  // The name was assigned by OAuth signup, not chosen. Replacing it is the
  // person's first actual choice, so it is never blocked and never charged.
  if (input.usernameAutoGenerated) {
    return ELIGIBLE;
  }

  if (!input.usernameChangedAt) {
    return ELIGIBLE;
  }

  const now = input.now ?? new Date();
  const availableAt = new Date(
    input.usernameChangedAt.getTime() + USERNAME_CHANGE_COOLDOWN_MS,
  );

  if (now.getTime() >= availableAt.getTime()) {
    return ELIGIBLE;
  }

  return {
    canChange: false,
    availableAt,
    retryAfterSeconds: Math.max(
      1,
      Math.ceil((availableAt.getTime() - now.getTime()) / 1000),
    ),
  };
}

/** True when the two values name the same profile, ignoring case and surrounding space. */
export function isSameUsername(left: string, right: string): boolean {
  return left.trim().toLowerCase() === right.trim().toLowerCase();
}
