import BadRequestError from "@/errors/http/bad-request.error";
import ConflictError from "@/errors/http/conflict.error";
import ResourceNotFoundError from "@/errors/http/resource-not-found.error";
import UsernameChangeCooldownError from "@/errors/http/username-change-cooldown.error";
import {
  USERNAME_CHANGE_COOLDOWN_DAYS,
  USERNAME_CHANGE_COOLDOWN_MS,
} from "@/features/profile/username-change-policy";
import type {
  ProfileRecord,
  PublicProfileRecord,
  UpdateProfileRecordInput,
} from "@/features/profile/profile.model";
import { ProfileService } from "@/features/profile/profile.service";
import { createMediaRule } from "../../support/media-rule";
import { testUuid } from "../../support/uuid";
const MISSING_USER_ID = testUuid(9000, 791594);

const PROFILE_1_ID = testUuid(9000, 548259);
const USER_1_ID = testUuid(9000, 994257);
const USER_42_ID = testUuid(9000, 822620);
const STORAGE_ORIGIN = "https://storage.example.com/";
const STORED_AVATAR_BLOB = `avatars/${USER_1_ID}.png`;
const STORED_AVATAR_URL = `${STORAGE_ORIGIN}${STORED_AVATAR_BLOB}`;

function createProfile(overrides: Partial<ProfileRecord> = {}): ProfileRecord {
  return {
    avatarVariants: null,
    id: PROFILE_1_ID,
    userId: USER_1_ID,
    email: "user@example.com",
    firstName: "Casey",
    lastName: "Doe",
    username: "casey-doe",
    usernameAutoGenerated: false,
    canChangeUsername: true,
    phoneNumber: "+1 555 0100",
    avatarUrl: `https://storage.example.com/avatars/${USER_1_ID}.png`,
    avatarBlobName: `avatars/${USER_1_ID}.png`,
    isPrivate: false,
    recommendationPersonalizationEnabled: true,
    recentlyViewedTrackingEnabled: true,
    trustworthinessScore: 4,
    rentPostingsCount: 3,
    availableRentPostingsCount: 2,
    createdAt: "2026-05-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
    ...overrides,
  };
}

function createPublicProfile(
  overrides: Partial<PublicProfileRecord> = {},
): PublicProfileRecord {
  return {
    avatarVariants: null,
    id: PROFILE_1_ID,
    userId: USER_1_ID,
    email: "user@example.com",
    firstName: "Casey",
    lastName: "Doe",
    username: "casey-doe",
    phoneNumber: "+1 555 0100",
    avatarUrl: `https://storage.example.com/avatars/${USER_1_ID}.png`,
    trustworthinessScore: 4,
    rentPostingsCount: 3,
    availableRentPostingsCount: 2,
    createdAt: "2026-05-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
    ...overrides,
  };
}

/**
 * Declared with a parameter so `mock.calls[0][0]` is indexable — tsconfig.test.json
 * infers an empty tuple for a `jest.fn()` with no signature.
 */
function createUpdateMock(result: ProfileRecord = createProfile()) {
  return jest.fn(async (_input: UpdateProfileRecordInput) => result);
}

/** The input the repository was called with, failing loudly if it never was. */
function firstUpdateInput(
  update: ReturnType<typeof createUpdateMock>,
): UpdateProfileRecordInput {
  const input = update.mock.calls[0]?.[0];

  if (!input) {
    throw new Error("Expected profileRepository.update to have been called.");
  }

  return input;
}

function createService(options?: {
  findByUserId?: jest.Mock;
  update?: jest.Mock;
  findPublicProfiles?: jest.Mock;
  assertUsernameIsAvailable?: jest.Mock;
}) {
  const profileRepository = {
    findPublicProfiles:
      options?.findPublicProfiles ??
      jest.fn(async () => ({
        profiles: [createPublicProfile()],
        pagination: {
          page: 1,
          pageSize: 20,
          total: 1,
          totalPages: 1,
          hasNextPage: false,
          hasPreviousPage: false,
        },
      })),
    findByUserId: options?.findByUserId ?? jest.fn(async () => createProfile()),
    update: options?.update ?? jest.fn(async () => createProfile()),
  };
  const mediaRule = createMediaRule({ origin: STORAGE_ORIGIN });
  const mediaService = {
    resolveImageReference: mediaRule.resolveImageReference,
  };
  const usernameService = {
    assertUsernameIsAvailable:
      options?.assertUsernameIsAvailable ?? jest.fn(async () => undefined),
  };
  const usernameBloomService = {
    check: jest.fn(() => "unknown" as const),
    add: jest.fn(async () => undefined),
  };

  return {
    profileRepository,
    mediaService,
    mediaRule,
    usernameService,
    usernameBloomService,
    service: new ProfileService(
      profileRepository as any,
      mediaService as any,
      usernameService as any,
      usernameBloomService as any,
    ),
  };
}

describe("ProfileService", () => {
  it("trims profile list queries and omits blank search strings", async () => {
    const { service, profileRepository } = createService();

    await service.list({
      page: 2,
      pageSize: 5,
      query: "  northwind  ",
    });
    await service.list({
      page: 1,
      pageSize: 10,
      query: "   ",
    });

    expect(profileRepository.findPublicProfiles).toHaveBeenNthCalledWith(1, {
      page: 2,
      pageSize: 5,
      query: "northwind",
    });
    expect(profileRepository.findPublicProfiles).toHaveBeenNthCalledWith(2, {
      page: 1,
      pageSize: 10,
      query: undefined,
    });
  });

  it("throws ResourceNotFoundError when reading a missing profile", async () => {
    const { service } = createService({
      findByUserId: jest.fn(async () => null),
    });

    await expect(service.getByUserId(MISSING_USER_ID)).rejects.toBeInstanceOf(
      ResourceNotFoundError,
    );
  });

  it("returns the resolved profile when reading by user id", async () => {
    const expectedProfile = createProfile({
      userId: USER_42_ID,
    });
    const { service } = createService({
      findByUserId: jest.fn(async () => expectedProfile),
    });

    await expect(service.getByUserId(USER_42_ID)).resolves.toBe(
      expectedProfile,
    );
  });

  it("resolves a new avatar from media uploaded for avatars", async () => {
    const update = createUpdateMock();
    const { service, mediaRule } = createService({ update });
    const avatar = mediaRule.addReadyMedia(
      USER_1_ID,
      testUuid(9000, 994350),
      "avatars",
    );

    await service.update({
      userId: USER_1_ID,
      username: "owner-one",
      avatarMediaId: avatar.mediaId,
    });

    const input = firstUpdateInput(update);
    expect(input).toMatchObject({
      avatarBlobName: avatar.blobName,
      avatarUrl: avatar.blobUrl,
    });
    expect(input).not.toHaveProperty("avatarMediaId");
  });

  it("refuses an avatar uploaded for another purpose", async () => {
    const { service, mediaRule, profileRepository } = createService();
    const photo = mediaRule.addReadyMedia(
      USER_1_ID,
      testUuid(9000, 994352),
      "postings",
    );

    await expect(
      service.update({
        userId: USER_1_ID,
        username: "owner-one",
        avatarMediaId: photo.mediaId,
      }),
    ).rejects.toThrow("Image was not uploaded for avatars.");
    expect(profileRepository.update).not.toHaveBeenCalled();
  });

  it("refuses an avatar media id sent alongside a blob reference", async () => {
    const { service, profileRepository } = createService();

    await expect(
      service.update({
        userId: USER_1_ID,
        username: "owner-one",
        avatarMediaId: testUuid(9000, 994351),
        avatarUrl: `${STORAGE_ORIGIN}avatars/a.png`,
        avatarBlobName: "avatars/a.png",
      }),
    ).rejects.toThrow(
      "Send either avatarMediaId or avatarUrl and avatarBlobName, not both.",
    );
    expect(profileRepository.update).not.toHaveBeenCalled();
  });

  it("normalizes profile updates before saving", async () => {
    const updatedProfile = createProfile({
      username: "owner-one",
      phoneNumber: "+1 555 0111",
    });
    const update = jest.fn(async () => updatedProfile);
    const { service, profileRepository } = createService({ update });

    await expect(
      service.update({
        userId: USER_1_ID,
        username: "  Owner-One  ",
        phoneNumber: "  +1 555 0111  ",
        isPrivate: true,
        // The stored avatar, resent with stray whitespace.
        avatarUrl: `  ${STORED_AVATAR_URL}  `,
        avatarBlobName: `  ${STORED_AVATAR_BLOB}  `,
        recommendationPersonalizationEnabled: false,
        trustworthinessScore: 5,
        rentPostingsCount: 6,
        availableRentPostingsCount: 4,
      }),
    ).resolves.toEqual(updatedProfile);

    expect(profileRepository.findByUserId).toHaveBeenCalledWith(USER_1_ID);
    expect(update).toHaveBeenCalledWith({
      userId: USER_1_ID,
      username: "owner-one",
      // This update renames the profile, so it starts the cooldown clock and
      // carries the guard the database re-tests eligibility with.
      usernameChangedAt: expect.any(Date),
      usernameChangeGuardAt: expect.any(Date),
      phoneNumber: "+1 555 0111",
      isPrivate: true,
      avatarUrl: STORED_AVATAR_URL,
      avatarBlobName: STORED_AVATAR_BLOB,
      recommendationPersonalizationEnabled: false,
      trustworthinessScore: 5,
      rentPostingsCount: 6,
      availableRentPostingsCount: 4,
    });
  });

  it("rejects updates when available postings exceed the total count", async () => {
    const { service } = createService();

    await expect(
      service.update({
        userId: USER_1_ID,
        username: "owner-one",
        rentPostingsCount: 1,
        availableRentPostingsCount: 2,
      }),
    ).rejects.toMatchObject({
      message:
        "Available rent postings count cannot exceed total rent postings count.",
    });
  });

  it("rejects an avatar URL and blob name that are not sent together", async () => {
    const { service } = createService();
    const message =
      "avatarUrl and avatarBlobName must be sent together, or both be null.";

    await expect(
      service.update({
        userId: USER_1_ID,
        username: "owner-one",
        avatarUrl: STORED_AVATAR_URL,
      }),
    ).rejects.toThrow(message);
    await expect(
      service.update({
        userId: USER_1_ID,
        username: "owner-one",
        avatarUrl: null,
        avatarBlobName: STORED_AVATAR_BLOB,
      }),
    ).rejects.toThrow(message);
  });

  it("refuses a new avatar sent by blob name, even one the user uploaded", async () => {
    const update = createUpdateMock();
    const { service } = createService({ update });

    await expect(
      service.update({
        userId: USER_1_ID,
        username: "casey-doe",
        avatarUrl: `${STORAGE_ORIGIN}avatars/${USER_1_ID}-new.png`,
        avatarBlobName: `avatars/${USER_1_ID}-new.png`,
      }),
    ).rejects.toThrow(
      "A new image must be uploaded and sent as avatarMediaId.",
    );
    expect(update).not.toHaveBeenCalled();
  });

  it("accepts the stored avatar again, and rejects it with a mismatched URL", async () => {
    const { service } = createService();

    await expect(
      service.update({
        userId: USER_1_ID,
        username: "casey-doe",
        avatarUrl: STORED_AVATAR_URL,
        avatarBlobName: `  ${STORED_AVATAR_BLOB}  `,
      }),
    ).resolves.toBeDefined();
    await expect(
      service.update({
        userId: USER_1_ID,
        username: "casey-doe",
        avatarUrl: `https://cdn.example.com/avatars/${USER_1_ID}.png`,
        avatarBlobName: STORED_AVATAR_BLOB,
      }),
    ).rejects.toThrow(
      "avatarUrl does not match the stored image for avatarBlobName.",
    );
  });

  it("allows clearing avatar fields together", async () => {
    const update = createUpdateMock(
      createProfile({
        avatarUrl: undefined,
        avatarBlobName: undefined,
      }),
    );
    const { service } = createService({ update });

    await service.update({
      userId: USER_1_ID,
      username: "owner-one",
      avatarUrl: null,
      avatarBlobName: null,
    });

    expect(update).toHaveBeenCalledWith({
      userId: USER_1_ID,
      username: "owner-one",
      // Renames away from the seeded "casey-doe", so the clock starts.
      usernameChangedAt: expect.any(Date),
      usernameChangeGuardAt: expect.any(Date),
      // Explicit nulls clear the avatar...
      avatarUrl: null,
      avatarBlobName: null,
    });
    // ...but the omitted phone number is not touched.
    expect(firstUpdateInput(update)).not.toHaveProperty("phoneNumber");
  });

  it("throws ResourceNotFoundError when updating a missing profile", async () => {
    const { service } = createService({
      findByUserId: jest.fn(async () => null),
    });

    await expect(
      service.update({
        userId: MISSING_USER_ID,
        username: "owner-one",
      }),
    ).rejects.toBeInstanceOf(ResourceNotFoundError);
  });

  describe("partial updates", () => {
    it("leaves an omitted phone number and avatar untouched", async () => {
      // The account page's "Save profile" sends only these three fields. It used
      // to silently wipe the saved phone number and avatar.
      const update = createUpdateMock();
      const { service } = createService({ update });

      await service.update({
        userId: USER_1_ID,
        username: "casey-doe",
        isPrivate: true,
        recommendationPersonalizationEnabled: false,
      });

      const data = firstUpdateInput(update);
      expect(data).not.toHaveProperty("phoneNumber");
      expect(data).not.toHaveProperty("avatarUrl");
      expect(data).not.toHaveProperty("avatarBlobName");
      expect(data).toMatchObject({ isPrivate: true });
    });

    it("clears a phone number when it is explicitly null", async () => {
      const update = createUpdateMock();
      const { service } = createService({ update });

      await service.update({
        userId: USER_1_ID,
        username: "casey-doe",
        phoneNumber: null,
      });

      expect(update).toHaveBeenCalledWith(
        expect.objectContaining({ phoneNumber: null }),
      );
    });

    it("normalizes a blank phone number to null defensively", async () => {
      // Not reachable through the API — `updateProfileRequestSchema` trims and
      // then enforces a 7-character minimum, so a blank value is rejected with
      // a 400 before the service sees it. `null` is the documented clear.
      const update = createUpdateMock();
      const { service } = createService({ update });

      await service.update({
        userId: USER_1_ID,
        username: "casey-doe",
        phoneNumber: "   ",
      });

      expect(update).toHaveBeenCalledWith(
        expect.objectContaining({ phoneNumber: null }),
      );
    });

    it("still saves a phone number without disturbing the avatar", async () => {
      // The account page's separate phone save, which omits the avatar pair.
      const update = createUpdateMock();
      const { service } = createService({ update });

      await service.update({
        userId: USER_1_ID,
        username: "casey-doe",
        phoneNumber: "  +1 555 0199  ",
      });

      const data = firstUpdateInput(update);
      expect(data.phoneNumber).toBe("+1 555 0199");
      expect(data).not.toHaveProperty("avatarUrl");
      expect(data).not.toHaveProperty("avatarBlobName");
    });
  });

  describe("username change cooldown", () => {
    it("leaves the cooldown untouched when the username is resent unchanged", async () => {
      // The PUT body always carries a username, so saving a phone number or an
      // avatar must not spend the allowance.
      const update = createUpdateMock();
      const { service, usernameService } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({
            username: "casey-doe",
            usernameChangedAt: "2026-08-16T12:00:00.000Z",
            canChangeUsername: false,
          }),
        ),
        update,
      });

      await service.update({
        userId: USER_1_ID,
        username: "  Casey-Doe  ",
        phoneNumber: "+1 555 0199",
      });

      const data = firstUpdateInput(update);
      expect(data).not.toHaveProperty("usernameChangedAt");
      expect(data).not.toHaveProperty("usernameAutoGenerated");
      expect(usernameService.assertUsernameIsAvailable).not.toHaveBeenCalled();
    });

    it("allows an unchanged legacy username that the current policy would reject", async () => {
      const update = createUpdateMock();
      const { service, usernameService } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({ username: "friendlyshittyperson" }),
        ),
        update,
      });

      await service.update({
        userId: USER_1_ID,
        username: "friendlyshittyperson",
        isPrivate: true,
      });

      expect(update).toHaveBeenCalled();
      expect(usernameService.assertUsernameIsAvailable).not.toHaveBeenCalled();
    });

    it("allows an unchanged legacy username without screening it again", async () => {
      const update = createUpdateMock();
      const { service, usernameService } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({ username: "friendlyshittyperson" }),
        ),
        update,
      });

      await service.update({
        userId: USER_1_ID,
        username: "friendlyshittyperson",
        phoneNumber: "+1 555 0199",
      });

      expect(usernameService.assertUsernameIsAvailable).not.toHaveBeenCalled();
      expect(update).toHaveBeenCalled();
    });

    it("rejects a rename made inside the cooldown window", async () => {
      const changedAt = new Date(Date.now() - 10 * 24 * 60 * 60 * 1000);
      const update = createUpdateMock();
      const { service } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({
            username: "casey-doe",
            usernameChangedAt: changedAt.toISOString(),
            canChangeUsername: false,
          }),
        ),
        update,
      });

      const error = await service
        .update({ userId: USER_1_ID, username: "casey-two" })
        .catch((caught: unknown) => caught);

      expect(error).toBeInstanceOf(UsernameChangeCooldownError);
      expect((error as UsernameChangeCooldownError).status).toBe(429);
      expect((error as UsernameChangeCooldownError).code).toBe(
        "USERNAME_CHANGE_COOLDOWN",
      );
      expect((error as UsernameChangeCooldownError).details).toEqual({
        availableAt: new Date(
          changedAt.getTime() + USERNAME_CHANGE_COOLDOWN_MS,
        ).toISOString(),
        retryAfterSeconds: expect.any(Number),
        cooldownDays: USERNAME_CHANGE_COOLDOWN_DAYS,
      });
      expect(update).not.toHaveBeenCalled();
    });

    it("starts the cooldown on a rename once the window has elapsed", async () => {
      const update = createUpdateMock();
      const { service, usernameService } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({
            username: "casey-doe",
            usernameChangedAt: new Date(
              Date.now() - (USERNAME_CHANGE_COOLDOWN_MS + 1000),
            ).toISOString(),
          }),
        ),
        update,
      });

      await service.update({ userId: USER_1_ID, username: "casey-two" });

      expect(update).toHaveBeenCalledWith(
        expect.objectContaining({
          username: "casey-two",
          usernameChangedAt: expect.any(Date),
        }),
      );
      expect(usernameService.assertUsernameIsAvailable).toHaveBeenCalledWith(
        "casey-two",
        USER_1_ID,
      );
    });

    it("records a completed rename in the username filter", async () => {
      const { service, usernameBloomService } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({
            username: "casey-doe",
            usernameChangedAt: new Date(
              Date.now() - (USERNAME_CHANGE_COOLDOWN_MS + 1000),
            ).toISOString(),
          }),
        ),
        update: createUpdateMock(),
      });

      await service.update({ userId: USER_1_ID, username: "Casey-Two" });

      expect(usernameBloomService.add).toHaveBeenCalledWith("casey-two");
    });

    it("leaves the filter alone when the username was resent unchanged", async () => {
      const { service, usernameBloomService } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({ username: "casey-doe" }),
        ),
        update: createUpdateMock(),
      });

      await service.update({ userId: USER_1_ID, username: "casey-doe" });

      expect(usernameBloomService.add).not.toHaveBeenCalled();
    });

    it("claims an auto-generated username without starting the cooldown", async () => {
      // The OAuth welcome modal replacing a name the person never chose.
      const update = createUpdateMock();
      const { service } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({
            username: "casey.doe",
            usernameAutoGenerated: true,
          }),
        ),
        update,
      });

      await service.update({ userId: USER_1_ID, username: "casey-two" });

      const data = firstUpdateInput(update);
      expect(data).toMatchObject({
        username: "casey-two",
        usernameAutoGenerated: false,
      });
      expect(data).not.toHaveProperty("usernameChangedAt");
    });

    it("guards the write so the database re-tests eligibility", async () => {
      const update = createUpdateMock();
      const { service } = createService({ update });

      await service.update({ userId: USER_1_ID, username: "casey-two" });

      expect(firstUpdateInput(update).usernameChangeGuardAt).toBeInstanceOf(
        Date,
      );
    });

    it("does not guard an ordinary save", async () => {
      const update = createUpdateMock();
      const { service } = createService({ update });

      await service.update({ userId: USER_1_ID, username: "casey-doe" });

      expect(firstUpdateInput(update)).not.toHaveProperty(
        "usernameChangeGuardAt",
      );
    });

    it("reports the cooldown when a concurrent rename won the race", async () => {
      // The repository returns null when the guarded write matched no row.
      const changedAt = new Date(Date.now() - 60 * 1000);
      const update = jest.fn(
        async (_input: UpdateProfileRecordInput) => null,
      ) as unknown as ReturnType<typeof createUpdateMock>;
      const { service } = createService({
        update: update as unknown as jest.Mock,
        findByUserId: jest
          .fn(async () => createProfile())
          // First read: eligible. Second read (after the lost race): not.
          .mockResolvedValueOnce(createProfile())
          .mockResolvedValueOnce(
            createProfile({ usernameChangedAt: changedAt.toISOString() }),
          ),
      });

      const error = await service
        .update({ userId: USER_1_ID, username: "casey-two" })
        .catch((caught: unknown) => caught);

      expect(error).toBeInstanceOf(UsernameChangeCooldownError);
      expect((error as UsernameChangeCooldownError).details).toMatchObject({
        cooldownDays: USERNAME_CHANGE_COOLDOWN_DAYS,
        availableAt: new Date(
          changedAt.getTime() + USERNAME_CHANGE_COOLDOWN_MS,
        ).toISOString(),
      });
    });

    it("rejects a rename onto a username reserved by an unverified signup", async () => {
      const update = createUpdateMock();
      const { service } = createService({
        update,
        assertUsernameIsAvailable: jest.fn(async () => {
          throw new ConflictError("That username is already taken.", {
            field: "username",
          });
        }),
      });

      await expect(
        service.update({ userId: USER_1_ID, username: "casey-two" }),
      ).rejects.toBeInstanceOf(ConflictError);

      expect(update).not.toHaveBeenCalled();
    });

    it("rejects an inappropriate rename before persistence", async () => {
      const update = createUpdateMock();
      const { service } = createService({
        update,
        assertUsernameIsAvailable: jest.fn(async () => {
          throw new BadRequestError("That username isn’t allowed.", {
            field: "username",
            reason: "inappropriate",
          });
        }),
      });

      await expect(
        service.update({
          userId: USER_1_ID,
          username: "friendlyshittyperson",
        }),
      ).rejects.toMatchObject({
        status: 400,
        details: { field: "username", reason: "inappropriate" },
      });
      expect(update).not.toHaveBeenCalled();
    });
  });
});
