import BadRequestError from "@/errors/http/bad-request.error";
import ConflictError from "@/errors/http/conflict.error";
import ResourceNotFoundError from "@/errors/http/resource-not-found.error";
import UsernameChangeCooldownError from "@/errors/http/username-change-cooldown.error";
import {
  USERNAME_CHANGE_COOLDOWN_DAYS,
  USERNAME_CHANGE_COOLDOWN_MS,
} from "@/features/profile/username-change-policy";
import type {
  ProfileRecord,
  PublicProfileRecord,
} from "@/features/profile/profile.model";
import { ProfileService } from "@/features/profile/profile.service";

function createProfile(overrides: Partial<ProfileRecord> = {}): ProfileRecord {
  return {
    id: "profile-1",
    userId: "user-1",
    email: "user@example.com",
    firstName: "Casey",
    lastName: "Doe",
    username: "casey-doe",
    usernameAutoGenerated: false,
    canChangeUsername: true,
    phoneNumber: "+1 555 0100",
    avatarUrl: "https://storage.example.com/avatars/user-1.png",
    avatarBlobName: "avatars/user-1.png",
    isPrivate: false,
    recommendationPersonalizationEnabled: true,
    trustworthinessScore: 4,
    rentPostingsCount: 3,
    availableRentPostingsCount: 2,
    createdAt: "2026-05-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
    ...overrides,
  };
}

function createPublicProfile(
  overrides: Partial<PublicProfileRecord> = {},
): PublicProfileRecord {
  return {
    id: "profile-1",
    userId: "user-1",
    email: "user@example.com",
    firstName: "Casey",
    lastName: "Doe",
    username: "casey-doe",
    phoneNumber: "+1 555 0100",
    avatarUrl: "https://storage.example.com/avatars/user-1.png",
    trustworthinessScore: 4,
    rentPostingsCount: 3,
    availableRentPostingsCount: 2,
    createdAt: "2026-05-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
    ...overrides,
  };
}

function createService(options?: {
  findByUserId?: jest.Mock;
  update?: jest.Mock;
  findPublicProfiles?: jest.Mock;
  isConfigured?: jest.Mock;
  isManagedBlobUrl?: jest.Mock;
  getJson?: jest.Mock;
}) {
  const profileRepository = {
    findPublicProfiles:
      options?.findPublicProfiles ??
      jest.fn(async () => ({
        profiles: [createPublicProfile()],
        pagination: {
          page: 1,
          pageSize: 20,
          total: 1,
          totalPages: 1,
          hasNextPage: false,
          hasPreviousPage: false,
        },
      })),
    findByUserId: options?.findByUserId ?? jest.fn(async () => createProfile()),
    update: options?.update ?? jest.fn(async () => createProfile()),
  };
  const blobService = {
    isConfigured: options?.isConfigured ?? jest.fn(() => true),
    isManagedBlobUrl: options?.isManagedBlobUrl ?? jest.fn(() => true),
  };
  const cacheService = {
    getJson: options?.getJson ?? jest.fn(async () => null),
  };

  return {
    profileRepository,
    blobService,
    cacheService,
    service: new ProfileService(
      profileRepository as any,
      blobService as any,
      cacheService as any,
    ),
  };
}

describe("ProfileService", () => {
  it("trims profile list queries and omits blank search strings", async () => {
    const { service, profileRepository } = createService();

    await service.list({
      page: 2,
      pageSize: 5,
      query: "  northwind  ",
    });
    await service.list({
      page: 1,
      pageSize: 10,
      query: "   ",
    });

    expect(profileRepository.findPublicProfiles).toHaveBeenNthCalledWith(1, {
      page: 2,
      pageSize: 5,
      query: "northwind",
    });
    expect(profileRepository.findPublicProfiles).toHaveBeenNthCalledWith(2, {
      page: 1,
      pageSize: 10,
      query: undefined,
    });
  });

  it("throws ResourceNotFoundError when reading a missing profile", async () => {
    const { service } = createService({
      findByUserId: jest.fn(async () => null),
    });

    await expect(service.getByUserId("missing-user")).rejects.toBeInstanceOf(
      ResourceNotFoundError,
    );
  });

  it("returns the resolved profile when reading by user id", async () => {
    const expectedProfile = createProfile({
      userId: "user-42",
    });
    const { service } = createService({
      findByUserId: jest.fn(async () => expectedProfile),
    });

    await expect(service.getByUserId("user-42")).resolves.toBe(expectedProfile);
  });

  it("normalizes profile updates before saving", async () => {
    const updatedProfile = createProfile({
      username: "owner-one",
      phoneNumber: "+1 555 0111",
      avatarUrl: "https://storage.example.com/avatars/user-1-updated.png",
      avatarBlobName: "avatars/user-1-updated.png",
    });
    const update = jest.fn(async () => updatedProfile);
    const { service, profileRepository, blobService } = createService({
      update,
    });

    await expect(
      service.update({
        userId: "user-1",
        username: "  Owner-One  ",
        phoneNumber: "  +1 555 0111  ",
        isPrivate: true,
        avatarUrl: "  https://storage.example.com/avatars/user-1-updated.png  ",
        avatarBlobName: "  avatars/user-1-updated.png  ",
        recommendationPersonalizationEnabled: false,
        trustworthinessScore: 5,
        rentPostingsCount: 6,
        availableRentPostingsCount: 4,
      }),
    ).resolves.toEqual(updatedProfile);

    expect(profileRepository.findByUserId).toHaveBeenCalledWith("user-1");
    expect(blobService.isConfigured).toHaveBeenCalledTimes(1);
    expect(blobService.isManagedBlobUrl).toHaveBeenCalledWith(
      "  https://storage.example.com/avatars/user-1-updated.png  ",
      "  avatars/user-1-updated.png  ",
    );
    expect(update).toHaveBeenCalledWith({
      userId: "user-1",
      username: "owner-one",
      // This update renames the profile, so it starts the cooldown clock.
      usernameChangedAt: expect.any(Date),
      phoneNumber: "+1 555 0111",
      isPrivate: true,
      avatarUrl: "https://storage.example.com/avatars/user-1-updated.png",
      avatarBlobName: "avatars/user-1-updated.png",
      recommendationPersonalizationEnabled: false,
      trustworthinessScore: 5,
      rentPostingsCount: 6,
      availableRentPostingsCount: 4,
    });
  });

  it("rejects updates when available postings exceed the total count", async () => {
    const { service } = createService();

    await expect(
      service.update({
        userId: "user-1",
        username: "owner-one",
        rentPostingsCount: 1,
        availableRentPostingsCount: 2,
      }),
    ).rejects.toMatchObject({
      message:
        "Available rent postings count cannot exceed total rent postings count.",
    });
  });

  it("rejects updates when only one avatar field is provided", async () => {
    const { service } = createService();

    await expect(
      service.update({
        userId: "user-1",
        username: "owner-one",
        avatarUrl: "https://storage.example.com/avatars/user-1.png",
      }),
    ).rejects.toMatchObject({
      message:
        "Avatar URL and avatar blob name must be provided together when updating the avatar.",
    });
  });

  it("rejects updates when only the avatar blob name is provided", async () => {
    const { service } = createService();

    await expect(
      service.update({
        userId: "user-1",
        username: "owner-one",
        avatarUrl: null,
        avatarBlobName: "avatars/user-1.png",
      }),
    ).rejects.toMatchObject({
      message:
        "Avatar URL and avatar blob name must both be set or both be null.",
    });
  });

  it("allows clearing avatar fields together without blob storage checks", async () => {
    const update = jest.fn(async () =>
      createProfile({
        avatarUrl: undefined,
        avatarBlobName: undefined,
      }),
    );
    const { service, blobService } = createService({
      update,
      isConfigured: jest.fn(() => false),
    });

    await service.update({
      userId: "user-1",
      username: "owner-one",
      avatarUrl: null,
      avatarBlobName: null,
    });

    expect(blobService.isConfigured).not.toHaveBeenCalled();
    expect(update).toHaveBeenCalledWith({
      userId: "user-1",
      username: "owner-one",
      // Renames away from the seeded "casey-doe", so the clock starts.
      usernameChangedAt: expect.any(Date),
      // Explicit nulls clear the avatar...
      avatarUrl: null,
      avatarBlobName: null,
    });
    // ...but the omitted phone number is not touched.
    expect(update.mock.calls[0]?.[0]).not.toHaveProperty("phoneNumber");
  });

  it("rejects avatar uploads when blob storage is not configured", async () => {
    const { service } = createService({
      isConfigured: jest.fn(() => false),
    });

    await expect(
      service.update({
        userId: "user-1",
        username: "owner-one",
        avatarUrl: "https://storage.example.com/avatars/user-1.png",
        avatarBlobName: "avatars/user-1.png",
      }),
    ).rejects.toMatchObject({
      message:
        "Avatar images require Azure Blob Storage to be configured on the backend.",
    });
  });

  it("rejects avatar urls that do not match the managed blob location", async () => {
    const { service } = createService({
      isManagedBlobUrl: jest.fn(() => false),
    });

    await expect(
      service.update({
        userId: "user-1",
        username: "owner-one",
        avatarUrl: "https://cdn.example.com/avatars/user-1.png",
        avatarBlobName: "avatars/user-1.png",
      }),
    ).rejects.toMatchObject({
      message:
        "Avatar URL must match the Azure Blob Storage location for the provided blob name.",
    });
  });

  it("throws ResourceNotFoundError when updating a missing profile", async () => {
    const { service } = createService({
      findByUserId: jest.fn(async () => null),
    });

    await expect(
      service.update({
        userId: "missing-user",
        username: "owner-one",
      }),
    ).rejects.toBeInstanceOf(ResourceNotFoundError);
  });

  describe("partial updates", () => {
    it("leaves an omitted phone number and avatar untouched", async () => {
      // The account page's "Save profile" sends only these three fields. It used
      // to silently wipe the saved phone number and avatar.
      const update = jest.fn(async () => createProfile());
      const { service } = createService({ update });

      await service.update({
        userId: "user-1",
        username: "casey-doe",
        isPrivate: true,
        recommendationPersonalizationEnabled: false,
      });

      const data = update.mock.calls[0]?.[0] as Record<string, unknown>;
      expect(data).not.toHaveProperty("phoneNumber");
      expect(data).not.toHaveProperty("avatarUrl");
      expect(data).not.toHaveProperty("avatarBlobName");
      expect(data).toMatchObject({ isPrivate: true });
    });

    it("clears a phone number when it is explicitly null", async () => {
      const update = jest.fn(async () => createProfile());
      const { service } = createService({ update });

      await service.update({
        userId: "user-1",
        username: "casey-doe",
        phoneNumber: null,
      });

      expect(update).toHaveBeenCalledWith(
        expect.objectContaining({ phoneNumber: null }),
      );
    });

    it("clears a phone number when it is sent blank", async () => {
      const update = jest.fn(async () => createProfile());
      const { service } = createService({ update });

      await service.update({
        userId: "user-1",
        username: "casey-doe",
        phoneNumber: "   ",
      });

      expect(update).toHaveBeenCalledWith(
        expect.objectContaining({ phoneNumber: null }),
      );
    });

    it("still saves a phone number without disturbing the avatar", async () => {
      // The account page's separate phone save, which omits the avatar pair.
      const update = jest.fn(async () => createProfile());
      const { service } = createService({ update });

      await service.update({
        userId: "user-1",
        username: "casey-doe",
        phoneNumber: "  +1 555 0199  ",
      });

      const data = update.mock.calls[0]?.[0] as Record<string, unknown>;
      expect(data.phoneNumber).toBe("+1 555 0199");
      expect(data).not.toHaveProperty("avatarUrl");
      expect(data).not.toHaveProperty("avatarBlobName");
    });
  });

  describe("username change cooldown", () => {
    it("leaves the cooldown untouched when the username is resent unchanged", async () => {
      // The PUT body always carries a username, so saving a phone number or an
      // avatar must not spend the allowance.
      const update = jest.fn(async () => createProfile());
      const { service, cacheService } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({
            username: "casey-doe",
            usernameChangedAt: "2026-08-16T12:00:00.000Z",
            canChangeUsername: false,
          }),
        ),
        update,
      });

      await service.update({
        userId: "user-1",
        username: "  Casey-Doe  ",
        phoneNumber: "+1 555 0199",
      });

      const [call] = update.mock.calls;
      expect(call?.[0]).not.toHaveProperty("usernameChangedAt");
      expect(call?.[0]).not.toHaveProperty("usernameAutoGenerated");
      expect(cacheService.getJson).not.toHaveBeenCalled();
    });

    it("rejects a rename made inside the cooldown window", async () => {
      const changedAt = new Date(Date.now() - 10 * 24 * 60 * 60 * 1000);
      const update = jest.fn(async () => createProfile());
      const { service } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({
            username: "casey-doe",
            usernameChangedAt: changedAt.toISOString(),
            canChangeUsername: false,
          }),
        ),
        update,
      });

      const error = await service
        .update({ userId: "user-1", username: "casey-two" })
        .catch((caught: unknown) => caught);

      expect(error).toBeInstanceOf(UsernameChangeCooldownError);
      expect((error as UsernameChangeCooldownError).status).toBe(429);
      expect((error as UsernameChangeCooldownError).code).toBe(
        "USERNAME_CHANGE_COOLDOWN",
      );
      expect((error as UsernameChangeCooldownError).details).toEqual({
        availableAt: new Date(
          changedAt.getTime() + USERNAME_CHANGE_COOLDOWN_MS,
        ).toISOString(),
        retryAfterSeconds: expect.any(Number),
        cooldownDays: USERNAME_CHANGE_COOLDOWN_DAYS,
      });
      expect(update).not.toHaveBeenCalled();
    });

    it("starts the cooldown on a rename once the window has elapsed", async () => {
      const update = jest.fn(async () => createProfile());
      const { service } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({
            username: "casey-doe",
            usernameChangedAt: new Date(
              Date.now() - (USERNAME_CHANGE_COOLDOWN_MS + 1000),
            ).toISOString(),
          }),
        ),
        update,
      });

      await service.update({ userId: "user-1", username: "casey-two" });

      expect(update).toHaveBeenCalledWith(
        expect.objectContaining({
          username: "casey-two",
          usernameChangedAt: expect.any(Date),
        }),
      );
    });

    it("claims an auto-generated username without starting the cooldown", async () => {
      // The OAuth welcome modal replacing a name the person never chose.
      const update = jest.fn(async () => createProfile());
      const { service } = createService({
        findByUserId: jest.fn(async () =>
          createProfile({
            username: "casey.doe",
            usernameAutoGenerated: true,
          }),
        ),
        update,
      });

      await service.update({ userId: "user-1", username: "casey-two" });

      const [call] = update.mock.calls;
      expect(call?.[0]).toMatchObject({
        username: "casey-two",
        usernameAutoGenerated: false,
      });
      expect(call?.[0]).not.toHaveProperty("usernameChangedAt");
    });

    it("rejects a rename onto a username reserved by an unverified signup", async () => {
      const update = jest.fn(async () => createProfile());
      const { service } = createService({
        update,
        getJson: jest.fn(async () => "pending@example.com"),
      });

      await expect(
        service.update({ userId: "user-1", username: "casey-two" }),
      ).rejects.toBeInstanceOf(ConflictError);

      expect(update).not.toHaveBeenCalled();
    });
  });
});
