import {
  isSameUsername,
  resolveUsernameChangeEligibility,
  USERNAME_CHANGE_COOLDOWN_DAYS,
  USERNAME_CHANGE_COOLDOWN_MS,
} from "@/features/profile/username-change-policy";

const NOW = new Date("2026-08-17T12:00:00.000Z");

function daysBefore(date: Date, days: number): Date {
  return new Date(date.getTime() - days * 24 * 60 * 60 * 1000);
}

describe("resolveUsernameChangeEligibility", () => {
  it("allows a change when the clock has never started", () => {
    const result = resolveUsernameChangeEligibility({
      usernameChangedAt: null,
      usernameAutoGenerated: false,
      now: NOW,
    });

    expect(result).toEqual({
      canChange: true,
      availableAt: null,
      retryAfterSeconds: 0,
    });
  });

  it("always allows replacing an auto-generated username, even inside the cooldown", () => {
    const result = resolveUsernameChangeEligibility({
      usernameChangedAt: daysBefore(NOW, 1),
      usernameAutoGenerated: true,
      now: NOW,
    });

    expect(result.canChange).toBe(true);
    expect(result.availableAt).toBeNull();
  });

  it("blocks a change inside the cooldown and reports when it lifts", () => {
    const changedAt = daysBefore(NOW, 10);

    const result = resolveUsernameChangeEligibility({
      usernameChangedAt: changedAt,
      usernameAutoGenerated: false,
      now: NOW,
    });

    expect(result.canChange).toBe(false);
    expect(result.availableAt).toEqual(
      new Date(changedAt.getTime() + USERNAME_CHANGE_COOLDOWN_MS),
    );
    // 20 days left of the 30-day window.
    expect(result.retryAfterSeconds).toBe(20 * 24 * 60 * 60);
  });

  it("allows a change once the cooldown has fully elapsed", () => {
    const result = resolveUsernameChangeEligibility({
      usernameChangedAt: daysBefore(NOW, USERNAME_CHANGE_COOLDOWN_DAYS + 1),
      usernameAutoGenerated: false,
      now: NOW,
    });

    expect(result.canChange).toBe(true);
  });

  it("allows a change at exactly the cooldown boundary", () => {
    const result = resolveUsernameChangeEligibility({
      usernameChangedAt: new Date(NOW.getTime() - USERNAME_CHANGE_COOLDOWN_MS),
      usernameAutoGenerated: false,
      now: NOW,
    });

    expect(result.canChange).toBe(true);
  });

  it("blocks one millisecond before the boundary and never reports a zero retry", () => {
    const result = resolveUsernameChangeEligibility({
      usernameChangedAt: new Date(
        NOW.getTime() - USERNAME_CHANGE_COOLDOWN_MS + 1,
      ),
      usernameAutoGenerated: false,
      now: NOW,
    });

    expect(result.canChange).toBe(false);
    expect(result.retryAfterSeconds).toBe(1);
  });

  it("defaults to the current time when no clock is supplied", () => {
    const result = resolveUsernameChangeEligibility({
      usernameChangedAt: new Date(Date.now() - 1000),
      usernameAutoGenerated: false,
    });

    expect(result.canChange).toBe(false);
  });
});

describe("isSameUsername", () => {
  it.each([
    ["taylor", "taylor", true],
    ["Taylor", "taylor", true],
    ["  taylor  ", "taylor", true],
    ["taylor", "taylor-two", false],
  ])("compares %s and %s as %s", (left, right, expected) => {
    expect(isSameUsername(left, right)).toBe(expected);
  });
});
