import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { BlogPanel, emptyBlogForm } from "./blog-panel";
vi.mock("@/components/organizations/rich-text-editor", () => ({ RichTextEditor: ({ onChange }: {onChange:(value:string)=>void}) => <button onClick={() => onChange("<p>Body</p>")}>Edit body</button> }));
vi.mock("@/components/organizations/shared/format", () => ({ formatDate: () => "Today" }));
vi.mock("@/lib/organizations/urls", () => ({ organizationHref: (...parts: string[]) => `/organizations/${parts.join("/")}` }));
const post = { id: "post-1", organizationId: "org-1", title: "News", slug: "news", body: "Body", tags: ["release"], status: "published" as const, createdAt: "2026-01-01" };
function props(overrides = {}) { return { organizationId: "org-1", organizationSlug: "studio", posts: [post], loading: false, error: null, canManage: true, form: emptyBlogForm(), editingId: null, savingId: null, onFormChange: vi.fn(), onSubmit: vi.fn(), onCancelEdit: vi.fn(), onEdit: vi.fn(), onToggleStatus: vi.fn(), onDelete: vi.fn(), onError: vi.fn(), ...overrides }; }
describe("BlogPanel", () => {
  it("edits form fields and invokes post actions", () => { const p = props(); render(<BlogPanel {...p} />); fireEvent.change(screen.getByLabelText("Title"), { target: { value: "Launch" } }); expect(p.onFormChange).toHaveBeenCalledWith(expect.objectContaining({ title: "Launch" })); fireEvent.change(screen.getByPlaceholderText("Add a tag and press Enter"), { target: { value: "news" } }); fireEvent.keyDown(screen.getByPlaceholderText("Add a tag and press Enter"), { key: "Enter" }); expect(p.onFormChange).toHaveBeenCalledWith(expect.objectContaining({ tags: ["news"] })); fireEvent.click(screen.getByRole("button", { name: "Edit body" })); expect(p.onFormChange).toHaveBeenCalledWith(expect.objectContaining({ body: "<p>Body</p>" })); fireEvent.click(screen.getByRole("button", { name: "Unpublish" })); fireEvent.click(screen.getByRole("button", { name: "Edit" })); fireEvent.click(screen.getByRole("button", { name: "Delete" })); expect(p.onToggleStatus).toHaveBeenCalledWith(post); expect(p.onEdit).toHaveBeenCalledWith(post); expect(p.onDelete).toHaveBeenCalledWith("post-1"); expect(screen.getByRole("link", { name: "View public post" })).toHaveAttribute("href", "/organizations/studio/blog/news"); });
  it("renders loading, errors, and read-only empty content", () => { const { rerender } = render(<BlogPanel {...props({ posts: [], loading: true })} />); expect(screen.getByText("0 total")).toBeInTheDocument(); rerender(<BlogPanel {...props({ posts: [], loading: false, error: "Unavailable" })} />); expect(screen.getByText("Unavailable")).toBeInTheDocument(); rerender(<BlogPanel {...props({ posts: [], loading: false, canManage: false })} />); expect(screen.getByText("No blog posts yet.")).toBeInTheDocument(); });
});
